profile: local

application.name: yosep-payment-service

server:
  port: 8080
  logging:
    access: true
  shutdown: graceful

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/yosep-payment?useUnicode=true&characterEncoding=utf8&autoreconnect=true
    username: root
    password: 1111
    pool:
      max-size: 10
      max-idle-time: 100000ms

  thymeleaf:
    cache: false

  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - 127.0.0.1:9092
          - 127.0.0.1:9093
          - 127.0.0.1:9094
          required-acks: all
          auto-create-topics: false
        bindings:
          send-out-0:
            producer:
              record-metadata-channel: payment-result

      bindings:
        send-out-0:
          destination: payment
          group: payment-service


logging:
  level:
    org:
      springframework:
        web: DEBUG
#        r2dbc: DEBUG
#        transaction: DEBUG

PSP:
  toss:
    secretKey: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    url: https://api.tosspayments.com
management:
  endpoint:
    web:
      exposure:
        include: bindings
